# Generated by Django 3.0.8 on 2020-07-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200701_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
